### ISSUE TITLE
Main Menu is Misaligned After Exiting Session and Using Overview Button

### ISSUE THREAD

**Issue by thewizardstudio** [tube42/candymem#5]
#### EXPECTED BEHAVIOR
Main Menu is aligned properly after leaving a game using the back button, tapping the overview button and then tapping the game pane.

#### ACTUAL BEHAVIOR
Main Menu is misaligned after leaving a game using the back button, tapping the overview button and then tapping the game pane.

#### HOW TO REPRODUCE
1. Launch Candy Memory 1.6.0 on Android 8.1.0
2. Tap the Play icon
3. Tap the Back button
4. Quickly tap the Overview button
5. Tap the Back button to return to game

#### TESTING ENVIRONMENT
- **Device**: Pixel 2 XL <br>
- **OS**: Android 8.1.0 <br>
- **App Version**: 1.6.0 <br>

#### RECORDING OF THE BUG
![OverviewAlignment.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519790371/bb6ae75q8hp6c3x02tsq.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/main-menu-is-misaligned-after-exiting-session-and-using-overview-button">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tube42** [comment]
Not sure what you mean by "overview" button.

Your recording doesn't work so I can't figure out what you mean.

**Comment by tube42** [comment]
See if version 1.7.0 fixes this issue
